apiVersion: v1
kind: Pod
metadata:
  name: demo-pod2
  namespace: default
  labels:
    app: env-demo-pod
spec:
  containers:
  - name: env-demo-container
    image: nginx
    ports:
     - containerPort: 80
    envFrom:
     - configMapRef:
         name: env-demo-configmap

--- 