apiVersion: v1
kind: Secret 
metadata:
  name: my-secret
  namespace: default
data:
  username: dXNlclZlbmthdAo=
  password: bXlwYXNzd29yZEAzMwo=

---

apiVersion: v1
kind: Pod
metadata:
  name: demo-pod3
  namespace: default
  labels:
    app: env-demo-pod
spec:
  containers:
  - name: env-demo-container
    image: nginx
    ports:
     - containerPort: 80
    envFrom:
     - secretRef:
         name: my-secret
     - configMapRef:
         name: env-demo-configmap
