# Deployment for LoadBalancer demo
# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello 
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: myapp
        image: httpd
        ports:
          - containerPort: 80