# LoadBalancer service for cluster
# kubectl apply -f loadbalancer.yml
kind: Service
apiVersion: v1
metadata:
  name: my-loadbalancer-svc 
spec:
  type: LoadBalancer
  selector:
    app: hello 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80